version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL} # Use Supabase database URL directly
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
